version: '3.8'

services:
    # Laravel 應用服務
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - "8070:8000"
        depends_on:
            - mysql
        networks:
            - laravel_net

    # MySQL 8.0
    mysql:
        image: mysql:8.0
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel_net

networks:
    laravel_net:
        driver: bridge
