version: '3.8'

services:
    # Laravel 應用服務
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
#            - ./storage/app/database.sqlite:/var/www/html/database/database.sqlite
        ports:
            - "8080:8000"
        depends_on:
            - sqlite
        environment:
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite
        networks:
            - laravel_net

    # SQLite 服務
    sqlite:
        image: nouchka/sqlite3:latest
        container_name: sqlite_db
        stdin_open: true
        tty: true
        volumes:
            - ./storage/app/:/root/db/
        networks:
            - laravel_net

networks:
    laravel_net:
        driver: bridge
